_extends: .github

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # A short description of the repository that will show up on GitHub
  description: ðŸ”¹ Golang module

  # A comma-separated list of topics to set on the repository
  topics: atomicgo, go, golang, golang-library

  # Either `true` to make the repository private, or `false` to make it public.
  #  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  #  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  #  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  #  has_wiki: false
