on: push

name: AtomicGo
jobs:
  docs:
    if: "!contains(github.event.head_commit.message, 'autoupdate')"
    runs-on: ubuntu-latest
    steps:
      - name: Update Docs
        uses: atomicgo/ci@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TERM: xterm-256color
